export const groups = [
  {
    label: "Localisation",
    id: "localisation",
    type: "select",
    options: [
      "Select a city",
      "carlow",
      "clare",
      "cavan",
      "cork",
      "donegal",
      "dublin",
      "fermanagh",
      "galway",
      "kerry",
      "kildare",
      "kilkenny",
      "laois",
      "leitrim",
      "limerick",
      "longford",
      "louth",
      "mayo",
      "meath",
      "monaghan",
      "offaly",
      "roscommon",
      "sligo",
      "tipperary",
      "waterford",
      "westmeath",
      "wexford",
      "wicklow",
    ],
  },
  {
    label: "Number of bedrooms",
    id: "bedrooms",
    type: "input",
    min: 1,
    max: 7,
  },
  {
    label: "Number of bathrooms",
    id: "bathrooms",
    type: "input",
    min: 1,
    max: 7,
  },
  {
    label: "Floor area (m²)",
    id: "floorArea",
    type: "input",
    max: 1200,
  },
  {
    label: "Type of property",
    id: "propertyType",
    type: "select",
    options: [
      "Select a property",
      "apartment",
      "bungalow",
      "detached",
      "duplex",
      "end of terrace",
      "house",
      "semi-d",
      "studio",
      "terrace",
      "townhouse",
    ],
  },
  {
    label: "BER Rating",
    id: "berRating",
    type: "select",
    options: [
      "Select a rank",
      "a1",
      "a2",
      "a3",
      "b1",
      "b2",
      "b3",
      "c1",
      "c2",
      "c3",
      "d1",
      "d2",
      "e1",
      "e2",
      "f",
      "fg",
      "g",
    ],
  },
];
